/**
 * Order types for the Orderbook page (#10).
 *
 * Mirrors `apps/api/app/orders/schemas.py::OrderOut`. Money and quantity are
 * Pydantic `Decimal`, which serialises to a JSON **string** (`"3551.00"`), not
 * a number — so they are typed `string | null` and parsed at the point of
 * display. Typing them `number` compiles fine and then throws
 * `toFixed is not a function` in the browser.
 */
export interface OrderRow {
  po_id: number;
  po_number: string;
  order_number: string | null;
  supplier_ref_no: string | null;
  status: string;
  priority: string;

  vendor_id: number;
  vendor_name: string | null;

  project_id: number | null;
  project_name: string | null;
  location: string | null;

  /**
   * Q417/Q428: on a related part's order this is the PARENT's cutlist number —
   * the related part never holds one itself.
   */
  item_id: number | null;
  item_number: number | null;
  cutlist_no: string | null;

  category: string;
  description: string;
  product_code: string | null;
  product_description: string | null;

  quantity: string | null;
  unit_of_measure: string | null;
  unit_cost: string | null;
  total_amount: string | null;
  currency: string | null;

  required_date: string | null;
  date_ordered: string | null;
  due_date: string | null;

  notes: string | null;
  internal_comments: string | null;
  attributes: Record<string, unknown>;

  created_at: string;
  updated_at: string | null;

  /** §L Q511/Q512 — field-level optimistic concurrency. */
  field_versions: Record<string, number>;
  /** Server-computed: true for a Cancelled / Delivered order (read-only except
   *  `status`). The API enforces it; the UI only reads it to decide what to render. */
  locked: boolean;

  /** Why the order was rejected; set only while its status is Rejected. */
  rejection_note: string | null;

  cost_center_id: number | null;
  cost_center_code: string | null;
  cost_center_name: string | null;

  /** The Orderbook's old columns and HOME tab. Money is a Decimal, so a string. */
  requester_id: number | null;
  requester_name: string | null;
  requested_date: string | null;
  arrived_date: string | null;
  stock_tracked: boolean | null;
  gst_applicable: boolean | null;
  gst_included_in_price: boolean | null;
  /** Generated by the database from `total_amount` and the two GST flags. */
  gst_amount: string | null;
  grand_total: string | null;
  line_item_comments: string | null;
  changelog: string | null;
  product_website: string | null;
  has_attachment: boolean;
}

/** Pydantic `Decimal`, so the budget arrives as a string. */
export interface CostCentre {
  cost_center_id: number;
  code: string;
  name: string;
  budget_amount: string;
  is_active: boolean;
  /** From the budget ledger: what approved orders still hold, what delivered ones cost, the rest. */
  committed: string;
  spent: string;
  remaining: string;
}

/** `GET /orders/cost-breakdown` and `GET /projects/{id}/budget`: material cost by order type. */
export interface CostBreakdownOrder {
  po_id: number;
  po_number: string;
  status: string;
  vendor_name: string | null;
  description: string;
  product_code: string | null;
  total_amount: string;
  currency: string | null;
}

export interface CostBreakdownGroup {
  category: string;
  label: string;
  order_count: number;
  total: string;
  orders: CostBreakdownOrder[];
}

export interface CostBreakdown {
  groups: CostBreakdownGroup[];
  total: string;
}

export interface OrderCategory {
  category_key: string;
  label: string;
}

export interface OrderListOut {
  orders: OrderRow[];
}

export interface PatchOrderIn {
  // Omit a field to leave it alone. These five are refused if sent as an explicit
  // null (a 422) — the API has no "clear" for them — so they are not `| null`.
  vendor_id?: number;
  description?: string;
  category?: string;
  status?: string;
  priority?: string;
  order_number?: string | null;
  supplier_ref_no?: string | null;
  location?: string | null;
  product_code?: string | null;
  product_description?: string | null;
  quantity?: string | null;
  unit_of_measure?: string | null;
  unit_cost?: string | null;
  total_amount?: string | null;
  required_date?: string | null;
  date_ordered?: string | null;
  due_date?: string | null;
  notes?: string | null;
  internal_comments?: string | null;
  attributes?: Record<string, unknown> | null;
  arrived_date?: string | null;
  stock_tracked?: boolean;
  gst_applicable?: boolean;
  gst_included_in_price?: boolean;
  line_item_comments?: string | null;
  product_website?: string | null;
  expected_versions?: Record<string, number>;
}

/** Mirrors `orders/schemas.py::OrderLineOut`. */
export interface OrderLine {
  line_id: number;
  line_number: number;
  item_description: string;
  sku: string | null;
  quantity: string;
  unit: string | null;
  unit_price: string;
  line_total: string | null;
  material_table: string | null;
  material_id: number | null;
  attributes: Record<string, unknown>;
}

/** `GET /orders/{po_id}` — `OrderRow` plus the line items. */
export interface OrderDetail extends OrderRow {
  lines: OrderLine[];
}

/** Mirrors `orders/schemas.py::CreateOrderLineIn`. */
export interface CreateOrderLineIn {
  item_description: string;
  quantity: string;
  unit_price: string;
  sku?: string | null;
  unit?: string | null;
}

/** Mirrors `orders/schemas.py::PatchOrderLineIn`. No `expected_versions` —
 * field-level optimistic concurrency (§L) is scoped to the order header,
 * not individual lines. */
export interface PatchOrderLineIn {
  item_description?: string | null;
  sku?: string | null;
  quantity?: string | null;
  unit?: string | null;
  unit_price?: string | null;
}
